name: .NET API Automation Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

env:
  RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore 
      working-directory: TripadvisorApiAutomation

    - name: Build project
      run: dotnet build --no-restore --configuration Release
      working-directory: TripadvisorApiAutomation

    - name: Replace RapidAPI key in appsettings.Release.json
      run: sed -i "s|replace-at-runtime|${{ env.RAPIDAPI_KEY }}|g" TripadvisorApiFramework/appsettings.Release.json
      working-directory: TripadvisorApiAutomation

    - name: Run tests
      run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test_results.trx"
      working-directory: TripadvisorApiAutomation

    - name: Upload test logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: '**/*.log'

    - name: Upload test results (TRX)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/TestResults/*.trx'
